In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.io as pio
import json
import requests

In [2]:
pd.options.plotting.backend = 'plotly'  ## 백엔드 기본 설정 변경
pio.templates.default = 'plotly_white'  ## 템플릿 변경

In [12]:
global_dict = json.loads(requests.get('https://raw.githubusercontent.com/southkorea/southkorea-maps/master/kostat/2018/json/skorea-provinces-2018-geo.json').text)
local_dict = json.loads(requests.get('https://raw.githubusercontent.com/southkorea/southkorea-maps/master/kostat/2018/json/skorea-municipalities-2018-geo.json').text)
#--#
url = 'https://raw.githubusercontent.com/guebin/DV2022/main/posts/Energy/{}.csv'
prov = ['Seoul', 'Busan', 'Daegu', 'Incheon',
        'Gwangju', 'Daejeon', 'Ulsan', 'Sejongsi',
        'Gyeonggi-do', 'Gangwon-do', 'Chungcheongbuk-do',
        'Chungcheongnam-do', 'Jeollabuk-do', 'Jeollanam-do',
        'Gyeongsangbuk-do', 'Gyeongsangnam-do', 'Jeju-do']
df = pd.concat([pd.read_csv(url.format(p+y)).assign(년도=y, 시도=p) for p in prov for y in ['2018', '2019', '2020', '2021']]).reset_index(drop=True)\
.assign(년도 = lambda df: df.년도.astype(int))\
.set_index(['년도','시도','지역']).applymap(lambda x: int(str(x).replace(',','')))\
.reset_index()
df.head()

C:\Users\hollyriver\AppData\Local\Temp\ipykernel_9460\2433387610.py:12: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  .set_index(['년도','시도','지역']).applymap(lambda x: int(str(x).replace(',','')))\

,년도,시도,지역,건물동수,연면적,에너지사용량(TOE)/전기,에너지사용량(TOE)/도시가스,에너지사용량(TOE)/지역난방
0,2018,Seoul,종로구,17929,9141777,64818,82015,111
1,2018,Seoul,중구,10598,10056233,81672,75260,563
2,2018,Seoul,용산구,17201,10639652,52659,85220,12043
3,2018,Seoul,성동구,14180,11631770,60559,107416,0
4,2018,Seoul,광진구,21520,12054796,70609,130308,0

In [4]:
## 한글 이름 변환
df = df.assign(시도 = df.시도.map({l['properties']['name_eng']:l['properties']['name'] for l in global_dict['features']}))

In [5]:
df_global = pd.DataFrame([l['properties'] for l in global_dict['features']]).drop(['base_year', 'name_eng'], axis = 1)
df_local = pd.DataFrame([l['properties'] for l in local_dict['features']])\
.rename({'code' : 'local_code'}, axis = 1).assign(code = lambda _df : _df.local_code.str[:2])\
.drop(['base_year', 'name_eng'], axis = 1).rename({'name' : '지명'}, axis = 1)
## > 합하기 위해 코드 앞 두자리를 가져오고, 시와 구를 `-`로 나눠놓았다. merge를 위한 정보를 남겨두었다.

df_json = df_local.merge(df_global)\
.assign(title = lambda _df : _df.지명.map(lambda x : x.split('시')[0] + '시-' + x.split('시')[-1] if '시' in x and '구' in x and len(x) > 3 else x))\
.assign(지명 = lambda _df : _df.title.str.split('-').str[-1])\
.assign(on = lambda _df : _df.name + '-' + _df.지명)\
.drop(['지명', 'code', 'name'], axis = 1)\
.set_index('on').rename({'인천광역시-남구' : '인천광역시-미추홀구'}).reset_index()

df_small = df_json.loc[df_json.on == '인천광역시-미추홀구'].set_index('title').rename({'남구' : '미추홀구'}).reset_index()
df_json2 = pd.concat([df_json.loc[df_json.on != '인천광역시-미추홀구'], df_small], axis = 0).reset_index(drop = True)

In [6]:
df2 = df.assign(on = df.시도 + '-' + df.지역).merge(df_json2).drop(['on', '지역'], axis = 1).rename({'title' : '지역'}, axis = 1)

In [7]:
data = df2.loc[(df2.local_code.str[:2] == '11') | (df2.local_code.str[:2] == '23') | (df2.local_code.str[:2] == '31')].reset_index(drop = True)\
.assign(diff = lambda _df : _df['에너지사용량(TOE)/전기'] - _df['에너지사용량(TOE)/도시가스']).rename({'diff' : '에너지사용량차이(전기-도시가스)'}, axis = 1)

In [8]:
minimum = min(data['에너지사용량차이(전기-도시가스)'])
maximum = max(data['에너지사용량차이(전기-도시가스)'])

In [13]:
metro_dict = local_dict.copy()
metro_dict['features'] = [l for l in local_dict['features'] if (l['properties']['code'][:2] == '11') or (l['properties']['code'][:2] == '23') or (l['properties']['code'][:2] == '31')]

In [2]:
fig = px.choropleth_mapbox(
    data_frame = data,
    geojson = metro_dict,
    featureidkey = 'properties.code',
    locations = 'local_code',
    color = '에너지사용량차이(전기-도시가스)',
    range_color = [minimum, maximum],
    hover_data = ['시도', '지역'],
    opacity = 0.5,
    animation_frame = '년도',
    #---#
    mapbox_style = 'carto-positron',
    center = {'lat' : 37.5642135, 'lon' : 127.0016985},
    zoom = 7.5,
    height = 800,
    width = 750
)

fig.show(config = {'scrollZoom' : False})

In [15]:
g = df2.loc[(df2.시도 == '서울특별시') | (df2.지역 == '김포시')].reset_index(drop = True)\
.assign(total = lambda _df : _df['에너지사용량(TOE)/전기'] + _df['에너지사용량(TOE)/도시가스'] + _df['에너지사용량(TOE)/지역난방'])\
.drop(['에너지사용량(TOE)/전기', '에너지사용량(TOE)/도시가스', '에너지사용량(TOE)/지역난방', '연면적', '건물동수'], axis = 1).groupby('년도')

In [16]:
data_frame

       년도     시도 local_code   지역   total  summary    구별사용비율
0    2018  서울특별시      11010  종로구  146944  5600005  0.026240
1    2018  서울특별시      11020   중구  157495  5600005  0.028124
2    2018  서울특별시      11030  용산구  149922  5600005  0.026772
3    2018  서울특별시      11040  성동구  167975  5600005  0.029996
4    2018  서울특별시      11050  광진구  200917  5600005  0.035878
..    ...    ...        ...  ...     ...      ...       ...
99   2021  서울특별시      11220  서초구  464528  7857412  0.059120
100  2021  서울특별시      11230  강남구  696833  7857412  0.088685
101  2021  서울특별시      11240  송파구  516111  7857412  0.065685
102  2021  서울특별시      11250  강동구  271502  7857412  0.034554
103  2021    경기도      31230  김포시  207168  7857412  0.026366

[104 rows x 7 columns]

In [17]:
data_frame = pd.concat([df.assign(summary = df.total.sum()) for i, df in g]).assign(rate = lambda _df : _df.total / _df.summary).rename({'rate' : '구별사용비율'}, axis = 1).reset_index(drop = True)

In [18]:
minimum = min(data_frame.구별사용비율)
maximum = max(data_frame.구별사용비율)

In [3]:
# fig = px.choropleth_mapbox(
#     data_frame = data_frame,
#     geojson = local_dict,
#     featureidkey = 'properties.code',
#     locations = 'local_code',
#     color = '구별사용비율',
#     range_color = [minimum, maximum],
#     hover_data = ['시도', '지역'],
#     opacity = 0.5,
#     animation_frame = '년도',
#     #---#
#     mapbox_style = 'carto-positron',
#     center = {'lat' : 37.5612, 'lon' : 126.8228},
#     zoom = 9,
#     height = 800,
#     width = 750
# )

# fig.show(config = {'scrollZoom' : False})